### ISSUE TITLE
AspNetCore version?

### ISSUE THREAD

**Issue by ciel** [ivaylokenov/AspNet.Mvc.TypedRouting#10]
I notice all of the files here still use `Microsoft.AspNet` namespacing. Are they compatible with the libraries from `Microsoft.AspNetCore.*`, and if so, is there any plan to update the namespaces or perhaps add a secondary version that fits in with the core framework? Or would you accept a pull request that updates the namespaces?

**Comment by ivaylokenov** [comment]
@ciel I plan to update the library with every major release of the MVC framework. Currently waiting for RC2 and will upload new version to NuGet. If you need it as soon as possible, I can update the package to a specific build version, but need to know which one you are using. If you are willing to make a pull request, I will be very happy, however I can do it for you. +1

**Comment by axunonb** [comment]
RC2 is available now. Would be great to have an updated build of TypedRouting
.

**Comment by ivaylokenov** [comment]
@axunonb, it will be uploaded by tomorrow. :)

**Comment by axunonb** [comment]
Wow, great, thanks!

**Comment by ivaylokenov** [comment]
@ciel @axunonb Package updated: https://www.nuget.org/packages/AspNet.Mvc.TypedRouting
