### ISSUE TITLE
Update to work with AspNet.MVC Core 1.0.0.

### ISSUE THREAD

**Issue by skorunka** [ivaylokenov/AspNet.Mvc.TypedRouting#13]
System.TypeLoadException
Could not load type 'Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

Line 139:  				routes.UseTypedRouting();

**Comment by ivaylokenov** [comment]
Package will be updated in the next 48 hours. :)

**Comment by skorunka** [comment]
Lovely, tried by myself but did not find a replacement for "controllerActionDescriptor.RouteConstraints" (ExpressionRouteHelper.cs, Line 73). Thanks.

**Comment by ivaylokenov** [comment]
@skorunka I am sorry for the delay but I have been sick today. Will update the package as soon as I get better.

**Comment by ivaylokenov** [comment]
@skorunka Updating currently. FYI - the RouteConstraints was replaced by RouteValues - https://github.com/aspnet/Mvc/commit/af58c2e6b619697a1a57736e9e996bb4d7e6e7ee

**Comment by ivaylokenov** [comment]
@skorunka Package is now available on NuGet.

**Comment by skorunka** [comment]
@ivaylokenov Works! Great job mate.
