### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by skorunka** [ivaylokenov/AspNet.Mvc.TypedRouting#14]
_Layout.cshtml:

`@(this.Url.Action<TestController>(x => x.Index()))`

results in:

![image](https://cloud.githubusercontent.com/assets/218913/16540055/1c818df4-404e-11e6-9376-bd4b742337f0.png)

**Comment by ivaylokenov** [comment]
@skorunka Was this working before?

**Comment by skorunka** [comment]
You are right. i forgot to use extension "UseTypedRouting" in Startup.
Thank you.

**Comment by ivaylokenov** [comment]
I will keep this open in order to implement a friendlier exception message when people forget to call that method.
