### ISSUE TITLE
Working with async controller actions generates compiler warning CS4014

### ISSUE THREAD

**Issue by justdmitry** [ivaylokenov/AspNet.Mvc.TypedRouting#18]
For example I have controller action:

```
public async Task<IActionResult> DoSomething() { ... }
```

To redirect to this action, I use code like
```
return this.RedirectToAction<MyController>(c => c.DoSomething());
```

Which generates compiler warning:
> warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.

Redirection still works Ok, but this warnings are annoying.

**Comment by ivaylokenov** [comment]
@justdmitry Thank you. Will upload a fix in the next few days.

**Comment by ivaylokenov** [comment]
@justdmitry Package with a fix is now uploaded to NuGet.
