### ISSUE TITLE
Wrong route generated when linking from area to arealess controller

### ISSUE THREAD

**Issue by justdmitry** [ivaylokenov/AspNet.Mvc.TypedRouting#19]
Controller `AccountController` is located in default (root, non-area specific) part of my site, it has `Logout` action.

I have area `Admin` with controllers labeled with `[Area("admin")]` attribute.

My `Startup` class contains following code:
```
app.UseMvc(routes =>
{
    routes.UseTypedRouting();

    routes.MapRoute(
        name: "areaRoute",
        template: "{area:exists}/{controller=Home}/{action=Index}");

    routes.MapRoute(
        name: "default",
        template: "{controller=Home}/{action=Index}");
});
```

Everything looks correct according to [asp.net core docs](https://docs.asp.net/en/latest/mvc/controllers/areas.html)

Inside view in my Areas/Admin/Views/... I write:

`@Url.Action<MyNamespace.Controllers.AccountController>(c => c.Logout()) })`

And generated value is `/admin/account/logout`, which is incorrect. Must be `/account/logout`, because `AccountController` does not have `Area` attribute.

**Comment by ivaylokenov** [comment]
I will take a look. Providing area route value like in the original helpers methods should workaround this:

@Url.Action<MyNamespace.Controllers.AccountController>(c => c.Logout(), new { area = string.Empty }) })

**Comment by ivaylokenov** [comment]
@justdmitry Package with the fix uploaded to NuGet.
