### ISSUE TITLE
Get Action name without passing parameters

### ISSUE THREAD

**Issue by v-zmiycharov** [ivaylokenov/AspNet.Mvc.TypedRouting#24]
Let's say I have a method with one required parameter 

```
[HttpPost]
IActionResult Test(int id).
```

If I want it to be post parameter I can't use the
`Url.Action<HomeController>(c => c.Test())`
because I have to pass "id".

**Comment by ivaylokenov** [comment]
@v-zmiycharov The C# compiler does not allow such call. This is why there is a special `With` class. You can use it like this to specify no action arguments in the route values:

```c#
Url.Action<HomeController>(c => c.Test(With.No<int>()))
```
